<<<<<<< HEAD
name: CI Back-end
=======
name: CI Back-end Main
>>>>>>> cef18157abf6e0b8a4133011100d5d8a5eb81e70

on:
  push:
    branches:
      - 'main'
    paths:
      - 'sgcmapi/**'
  workflow_dispatch:
  workflow_call:
  pull_request:
    paths:
      - 'sgcmapi/**'

<<<<<<< HEAD

jobs:
  primeiro-job:
=======
jobs:
  compile:
>>>>>>> cef18157abf6e0b8a4133011100d5d8a5eb81e70
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
<<<<<<< HEAD
      - name: Maven Compile/Test
        working-directory: sgcmapi/
        run: mvn compile test
  
  merge:
    needs: [primeiro-job]
=======
      - name: Maven Compile
        working-directory: sgcmapi/
        run: mvn compile
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Maven Test
        working-directory: sgcmapi/
        run: mvn test
  merge:
    needs: [compile, test]
>>>>>>> cef18157abf6e0b8a4133011100d5d8a5eb81e70
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Filtro de arquivos
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            java:
              - '**/*.java'
<<<<<<< HEAD
      - name: Merge brach
=======
      - name: Merge branch
>>>>>>> cef18157abf6e0b8a4133011100d5d8a5eb81e70
        if: steps.filter.outputs.java == 'false'
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          target_branch: main
<<<<<<< HEAD
          github_token: ${{ github.token }}
=======
          github_token: ${{ github.token }}
>>>>>>> cef18157abf6e0b8a4133011100d5d8a5eb81e70
